version: "3.0"
networks:
  services-network:
    driver: bridge
volumes:
  postgres_data:
services:
  backend:
    build: .
    volumes:
      - .:/backend
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_PASSWORD: root
      DB_NAME: shop_database
      DB_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - services-network
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_init_scripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - services-network