"""empty message

Revision ID: 079327268744
Revises: fcf7224098c3
Create Date: 2023-04-22 22:07:26.469767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079327268744'
down_revision = 'fcf7224098c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clearance')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('clearance', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
