"""empty message

Revision ID: c83aa1b24031
Revises: 02d0ca29b375
Create Date: 2023-04-23 00:19:55.235154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83aa1b24031'
down_revision = '02d0ca29b375'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'img_url')
    # ### end Alembic commands ###
